import numpy as np

#This file is for running our neher and leitner analysis on the filtered genotypes

#Directory with the text files
textdataDir = '/net/feder/vol1/home/evromero/2021_hiv-rec/data/slimDatasets/2022_02_24_txt/'

#Directory we'll use to save all of the additional analysis files
dataDir = '/net/feder/vol1/home/evromero/2021_hiv-rec/data/slimDatasets/2022_02_24/'

#Directory with all of the scripts for our additional rules
ruleScriptDir = "/net/feder/vol1/home/evromero/2021_hiv-rec/bin/rule_scripts/"

# #For Desktop Dry run
# textdataDir = '/Volumes/feder-vol1/project/hiv_recombination/data/simulated/2022_02_24/'
# dataDir = '/Volumes/feder-vol1/home/evromero/2021_hiv-rec/data/slimDatasets/2022_02_24/'
# ruleScriptDir = "/Volumes/feder-vol1/home/evromero/2021_hiv-rec/bin/rule_scripts/"

#get the proper names of all the simulated directories
rho_vals = ['0.001', '1e-04', '1e-05', '2e-04', '2e-05', '2e-06']
reps = range(1,11)
# filetypes = ['mutation', 'recombination']
# full_dir_pattern_neher= dataDir + "mu1e-05_rho{rho_val}_Ne10000_M800_rep{rep}/neher_res/{filetype}"
# full_dir_neher = expand(full_dir_pattern_neher,
#         rho_val = rho_vals, rep = reps, filetype = filetypes)

#the patterns for the linkage results
full_dir_pattern_linkage = dataDir + "mu1e-05_rho{rho_val}_Ne10000_M800_rep{rep}/linkage/r2_and_D"
full_dir_linkage = expand(full_dir_pattern_linkage,
        rho_val = rho_vals, rep = reps)

full_dir_pattern_d_rat = dataDir + "mu1e-05_rho{rho_val}_Ne10000_M800_rep{rep}/linkage/d_ratio"
full_dir_pattern_d_rat = expand(full_dir_pattern_d_rat,
        rho_val = rho_vals, rep = reps)

#get the proper names of all the timepoint files
timepoint_nums = range(1, 8)

# timepoint_pattern = "slim_formatted_t{timepoint_num}"
timepoint_list = ["slim_formatted_t" + str(s) for s in timepoint_nums]


#Targets are outputs and dependencies are inputs
rule all:
    input:
     full_dir_pattern_d_rat

rule process_slim:
    input: 
     (textdataDir + "mu1e-05_rho{rho_val}_Ne10000_M800_rep{rep}/" + s + ".txt" for s in timepoint_list)
    output: 
     dataDir +  "mu1e-05_rho{rho_val}_Ne10000_M800_rep{rep}/timepoint_info.tsv",
     (dataDir + "mu1e-05_rho{rho_val}_Ne10000_M800_rep{rep}/numpy/" + s + ".npy" for s in timepoint_list)
    script: ruleScriptDir + "process_slim.py"


rule gen_loci_dfs:
    input: 
     dataDir +  "mu1e-05_rho{rho_val}_Ne10000_M800_rep{rep}/timepoint_info.tsv",
     (dataDir + "mu1e-05_rho{rho_val}_Ne10000_M800_rep{rep}/numpy/" + s + ".npy" for s in timepoint_list)
    output:
     dataDir + "mu1e-05_rho{rho_val}_Ne10000_M800_rep{rep}/analysis/FilteredGenotypes",
     dataDir + "mu1e-05_rho{rho_val}_Ne10000_M800_rep{rep}/analysis/FilteredLoci"
    script: ruleScriptDir + "gen_loci_dfs.py"


# rule neher_leitner:
#     input: 
#      dataDir + "mu1e-05_rho{rho_val}_Ne10000_M800_rep{rep}/analysis/FilteredGenotypes",
#      dataDir + "mu1e-05_rho{rho_val}_Ne10000_M800_rep{rep}/analysis/FilteredLoci"
#     output: 
#      dataDir + "mu1e-05_rho{rho_val}_Ne10000_M800_rep{rep}/neher_res/recombination",
#      dataDir + "mu1e-05_rho{rho_val}_Ne10000_M800_rep{rep}/neher_res/mutation"
#     script: ruleScriptDir + "neher_leitner.py"

rule calc_linkage:
    input:
     dataDir + "mu1e-05_rho{rho_val}_Ne10000_M800_rep{rep}/analysis/FilteredLoci",
     (dataDir + "mu1e-05_rho{rho_val}_Ne10000_M800_rep{rep}/numpy/" + s + ".npy" for s in timepoint_list)
    output:
     dataDir + "mu1e-05_rho{rho_val}_Ne10000_M800_rep{rep}/linkage/r2_and_D"
    script: ruleScriptDir + "calc_linkage.py"

rule calc_d_rat:
    input:
     dataDir + "mu1e-05_rho{rho_val}_Ne10000_M800_rep{rep}/linkage/r2_and_D"
    output:
     dataDir + "mu1e-05_rho{rho_val}_Ne10000_M800_rep{rep}/linkage/d_ratio"
    script: ruleScriptDir + "calc_d_rat.py"