import numpy as np
import os

#I am using this to run the autocorrelation analysis on the Zanini data

# #Directory we'll use to save all of the additional analysis files
# dataDir = '/net/feder/vol1/home/evromero/2021_hiv-rec/data/zanini_snakemake/'

# #Directory with all of the scripts for our additional rules
# ruleScriptDir = "/net/feder/vol1/home/evromero/2021_hiv-rec/bin/rule_scripts/"

#For Desktop Dry run
dataDir = '/Volumes/feder-vol1/home/evromero/2021_hiv-rec/data/zanini_snakemake/'
ruleScriptDir = "/Volumes/feder-vol1/home/evromero/2021_hiv-rec/bin/rule_scripts/"

#get the proper names of all the simulated directories
participant_nums = ['p1','p2','p3','p4','p5','p7','p8','p9','p10','p11']
fragments = ['F1', 'F2', 'F3', 'F4', 'F5', 'F6']
filetypes = ['mutation', 'recombination']
full_dir_pattern_neher= dataDir + "{par}_{frag}/neher_res/{filetype}"
full_dir_neher = expand(full_dir_pattern_neher,
        par = participant_nums, frag = fragments, filetype = filetypes)

#the patterns for the linkage results
full_dir_pattern_linkage = dataDir + "{par}_{frag}/linkage/r2_and_D"
full_dir_linkage = expand(full_dir_pattern_linkage,
        par = participant_nums, frag = fragments)

full_dir_pattern_d_rat = dataDir + "{par}_{frag}/linkage/d_ratio"
full_dir_pattern_d_rat = expand(full_dir_pattern_d_rat,
        par = participant_nums, frag = fragments)

#get the proper names of all the timepoint files
timepoint_dict = {}
#loop through the directories
for curr_dir in os.listdir(dataDir):
    if curr_dir[0] == '.':
        continue
    timepoint_list = []
    curr_info = curr_dir.split('_')
    #loop through the current timepoints
    for timepoint_file in os.listdir(dataDir + curr_dir + "/numpy/"):
        if timepoint_file.split('.')[-1] != 'npy':
            continue

        curr_timepoint = timepoint_file.split('_')[-1]
        curr_timepoint = curr_timepoint.split('.')[0]
        timepoint_list.append(dataDir + curr_dir + '/numpy/cocounts_' + curr_info[0] + \
            '_sample_' + curr_timepoint[1:] + "_" + curr_info[1] + "_" + curr_timepoint + ".npy")
    #in this dictionary the key is the directory and the value is a list of timepoints in it
    timepoint_dict[curr_dir] = timepoint_list

#make an input function that will feed the relevant timepoints to the rule inputs
def get_correct_times(wildcards):
    return timepoint_dict[ wildcards.par + '_' + wildcards.frag ]

#Targets are outputs and dependencies are inputs
rule all:
    input:
     full_dir_pattern_d_rat

rule gen_loci_dfs:
    input: 
     dataDir +  "{par}_{frag}/timepoint_info.tsv",
     get_correct_times
    output:
     dataDir + "{par}_{frag}/analysis/FilteredGenotypes",
     dataDir + "{par}_{frag}/analysis/FilteredLoci"
    script: ruleScriptDir + "gen_loci_dfs.py"


# # rule neher_leitner:
# #     input: 
# #      dataDir + "mu1e-05_rho{rho_val}_Ne10000_M800_rep{rep}/analysis/FilteredGenotypes",
# #      dataDir + "mu1e-05_rho{rho_val}_Ne10000_M800_rep{rep}/analysis/FilteredLoci"
# #     output: 
# #      dataDir + "mu1e-05_rho{rho_val}_Ne10000_M800_rep{rep}/neher_res/recombination",
# #      dataDir + "mu1e-05_rho{rho_val}_Ne10000_M800_rep{rep}/neher_res/mutation"
# #     script: ruleScriptDir + "neher_leitner.py"

rule calc_linkage:
    input:
     dataDir + "{par}_{frag}/analysis/FilteredLoci",
     get_correct_times

    output:
     dataDir + "{par}_{frag}/linkage/r2_and_D"
    script: ruleScriptDir + "calc_linkage.py"

rule calc_d_rat:
    input:
     dataDir + "{par}_{frag}/linkage/r2_and_D"
    output:
     dataDir + "{par}_{frag}/linkage/d_ratio"
    script: ruleScriptDir + "calc_d_rat.py"