import numpy as np
import shutil

#This file is for running our neher and leitner analysis on the filtered genotypes

#Directory with the text files
textDataDir = '/net/feder/vol1/home/evromero/2021_hiv-rec/data/slimDatasets/2022_09_07_neutral_txt/'
inDataDir = '/net/feder/vol1/home/evromero/2021_hiv-rec/data/slimDatasets/2022_09_07_neutral/'

#Directory we'll use to save all of the additional analysis files
dataDir = '/net/feder/vol1/home/evromero/2021_hiv-rec/data/slimDatasets/2022_09_07_neutral_lessFilter/'

#Directory with all of the scripts for our additional rules
ruleScriptDir = "/net/feder/vol1/home/evromero/2021_hiv-rec/bin/rule_scripts/"

# #For Desktop Dry run
# inDataDir = '/Volumes/feder-vol1/home/evromero/2021_hiv-rec/data/slimDatasets/2022_09_07_neutral/'
# dataDir = '/Volumes/feder-vol1/home/evromero/2021_hiv-rec/data/slimDatasets/2022_09_07_neutral_lessFilter/'
# ruleScriptDir = "/Volumes/feder-vol1/home/evromero/2021_hiv-rec/bin/rule_scripts/"

#get the proper names of all the simulated directories
rho_vals = ['0.001', '1e-04','2e-04' ,'1e-05', '2e-05', '2e-06' ]

reps = range(1,20)
sel_opts = ['neutral']

#the patterns for the linkage results
full_dir_pattern_linkage = dataDir + "mu1e-06_rho{rho_val}_Ne10000_M800_s{sel_opt}_rep{rep}/linkage/r2_and_D"
full_dir_linkage = expand(full_dir_pattern_linkage,
        rho_val = rho_vals, rep = reps, sel_opt = sel_opts)

full_dir_pattern_d_rat = dataDir + "mu1e-06_rho{rho_val}_Ne10000_M800_s{sel_opt}_rep{rep}/linkage/d_ratio"
full_dir_pattern_d_rat = expand(full_dir_pattern_d_rat,
        rho_val = rho_vals, rep = reps, sel_opt = sel_opts)

#get the proper names of all the timepoint files
timepoint_nums = range(1, 6)

# timepoint_pattern = "slim_formatted_t{timepoint_num}"
timepoint_list = ["slim_formatted_t" + str(s) + '_f1' for s in timepoint_nums]

#Targets are outputs and dependencies are inputs
rule all:
    input:
     full_dir_pattern_d_rat

rule copy_time_file:
    input: 
     textDataDir +  "mu1e-06_rho{rho_val}_Ne10000_M800_s{sel_opt}_rep{rep}/timepoint_info.tsv",
    output:
     inDataDir +  "mu1e-06_rho{rho_val}_Ne10000_M800_s{sel_opt}_rep{rep}/timepoint_info.tsv"
    shell:
        "cp " + textDataDir + "mu1e-06_rho{wildcards.rho_val}_Ne10000_M800_s{wildcards.sel_opt}_rep{wildcards.rep}/timepoint_info.tsv "
         + inDataDir + "mu1e-06_rho{wildcards.rho_val}_Ne10000_M800_s{wildcards.sel_opt}_rep{wildcards.rep}/timepoint_info.tsv"

rule calc_linkage:
    input:
     inDataDir +  "mu1e-06_rho{rho_val}_Ne10000_M800_s{sel_opt}_rep{rep}/timepoint_info.tsv",
     inDataDir + "mu1e-06_rho{rho_val}_Ne10000_M800_s{sel_opt}_rep{rep}/analysis/FilteredLoci",
     (inDataDir + "mu1e-06_rho{rho_val}_Ne10000_M800_s{sel_opt}_rep{rep}/numpy/" + s + ".npy" for s in timepoint_list),
    output:
     dataDir + "mu1e-06_rho{rho_val}_Ne10000_M800_s{sel_opt}_rep{rep}/linkage/r2_and_D"
    script: ruleScriptDir + "calc_linkage.py"

rule calc_d_rat:
    input:
     dataDir + "mu1e-06_rho{rho_val}_Ne10000_M800_s{sel_opt}_rep{rep}/linkage/r2_and_D"
    output:
     dataDir + "mu1e-06_rho{rho_val}_Ne10000_M800_s{sel_opt}_rep{rep}/linkage/d_ratio"
    script: ruleScriptDir + "calc_d_rat.py"